In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [48]:
# Ler arquivo
df_final = pd.read_csv('/home/linguica/isabelle/sprint4Final/results_merged.csv')

In [49]:
df_final.columns

Index(['KNR', 'Tempo_ZP7', 'Tempo_ZP5', 'Tempo_ZP5A', 'Tempo_ZP6', 'Tempo_CAB',
       'temFalha', '012001', '012002', '012003',
       ...
       'SECTION_ROL_00000004', 'SECTION_ROL_00000005', 'SECTION_ROL_00000007',
       'SECTION_ROL_00000008', 'SECTION_ROL_00000009', 'SECTION_ZP8_00000003',
       'UPSECOS_ALS_00000020', 'UPSECOS_ALS_00000025', 'UPSECOS_ALS_00000030',
       'UPSECOS_ALS_00000035'],
      dtype='object', length=298)

In [50]:
df_final.head()

KNR    Tempo_ZP7  Tempo_ZP5   Tempo_ZP5A    Tempo_ZP6  Tempo_CAB  \
0  2023-4026017  8929.583333        0.0  5059.483333  2023.933333        0.0   
1  2023-4056259    23.250000        0.0  1892.083333  5652.466667        0.0   
2  2023-4066230  1290.583333        0.0  4711.016667  1425.533333        0.0   
3  2023-4216062  1223.116667        0.0  1810.966667  9595.050000       87.5   
4  2023-4216104   251.283333        0.0  8261.833333  1717.616667        0.0   

   temFalha  012001  012002  012003  ...  SECTION_ROL_00000004  \
0         1       1       1       1  ...                     1   
1         1       1       1       1  ...                     1   
2         1       1       1       1  ...                     1   
3         1       1       1       1  ...                     1   
4         1       1       1       1  ...                     1   

   SECTION_ROL_00000005  SECTION_ROL_00000007  SECTION_ROL_00000008  \
0                     1                     1                     1   
1                     1                     1                     1   
2                     1                     1                     1   
3                     1                     1                     1   
4                     1                     1                     1   

   SECTION_ROL_00000009  SECTION_ZP8_00000003  UPSECOS_ALS_00000020  \
0                     1                     0                     0   
1                     1                     0                     1   
2                     1                     0                     0   
3                     1                     0                     0   
4                     0                     0                     1   

   UPSECOS_ALS_00000025  UPSECOS_ALS_00000030  UPSECOS_ALS_00000035  
0                     0                     0                     0  
1                     1                     1                     1  
2                     0                     0                     0  
3                     0                     0                     0  
4                     1                     1                     1  

[5 rows x 298 columns]

In [51]:
df_final

KNR    Tempo_ZP7  Tempo_ZP5   Tempo_ZP5A    Tempo_ZP6  \
0    2023-4026017  8929.583333   0.000000  5059.483333  2023.933333   
1    2023-4056259    23.250000   0.000000  1892.083333  5652.466667   
2    2023-4066230  1290.583333   0.000000  4711.016667  1425.533333   
3    2023-4216062  1223.116667   0.000000  1810.966667  9595.050000   
4    2023-4216104   251.283333   0.000000  8261.833333  1717.616667   
..            ...          ...        ...          ...          ...   
246  2024-2626243   733.783333   0.000000  1397.633333   749.083333   
247  2024-2626276   373.200000   0.000000   964.516667  1900.816667   
248  2024-2626342   146.433333   0.000000  2376.666667  1160.700000   
249  2024-2636309   590.650000   0.000000  1410.433333  2690.116667   
250  2024-2656115   169.166667  32.433333  1445.716667  1815.200000   

     Tempo_CAB  temFalha  012001  012002  012003  ...  SECTION_ROL_00000004  \
0          0.0         1       1       1       1  ...                     1   
1          0.0         1       1       1       1  ...                     1   
2          0.0         1       1       1       1  ...                     1   
3         87.5         1       1       1       1  ...                     1   
4          0.0         1       1       1       1  ...                     1   
..         ...       ...     ...     ...     ...  ...                   ...   
246        0.0         0       0       0       0  ...                     0   
247        0.0         0       0       0       0  ...                     0   
248        0.0         0       0       0       0  ...                     0   
249        0.0         0       0       0       0  ...                     0   
250        0.0         0       0       0       0  ...                     0   

     SECTION_ROL_00000005  SECTION_ROL_00000007  SECTION_ROL_00000008  \
0                       1                     1                     1   
1                       1                     1                     1   
2                       1                     1                     1   
3                       1                     1                     1   
4                       1                     1                     1   
..                    ...                   ...                   ...   
246                     0                     0                     0   
247                     0                     0                     0   
248                     0                     0                     0   
249                     0                     0                     0   
250                     0                     0                     0   

     SECTION_ROL_00000009  SECTION_ZP8_00000003  UPSECOS_ALS_00000020  \
0                       1                     0                     0   
1                       1                     0                     1   
2                       1                     0                     0   
3                       1                     0                     0   
4                       0                     0                     1   
..                    ...                   ...                   ...   
246                     0                     0                     0   
247                     0                     0                     0   
248                     0                     0                     0   
249                     0                     0                     0   
250                     0                     0                     0   

     UPSECOS_ALS_00000025  UPSECOS_ALS_00000030  UPSECOS_ALS_00000035  
0                       0                     0                     0  
1                       1                     1                     1  
2                       0                     0                     0  
3                       0                     0                     0  
4                       1                     1                     1  
..                    ... 

## Normalização dos dados de tempo

In [52]:
# Selecionar apenas as colunas numéricas para normalização
colunas_numericas = df_final.select_dtypes(include=['float64', 'int64']).columns

# Instanciar o MinMaxScaler
scaler = MinMaxScaler()

# Aplicar o scaler para as colunas numéricas
df_final[colunas_numericas] = scaler.fit_transform(df_final[colunas_numericas])

In [53]:
# Definir X como todas as colunas, exceto 'temFalha' e 'KNR'
X = df_final.drop(['temFalha', 'KNR'], axis=1).values

# Definir Y como a coluna 'temFalha'
Y = df_final['temFalha'].values


In [54]:
df_final['temFalha']


0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ... 
246    0.0
247    0.0
248    0.0
249    0.0
250    0.0
Name: temFalha, Length: 251, dtype: float64

In [55]:
X = np.expand_dims(X, axis=1)  # Adicionando uma dimensão de tempo

In [56]:
len(Y)

251

Divisão dos dados de treino e de teste

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [58]:
y_test


array([0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.])

In [59]:
print(f'X_train dtype: {X_train.dtype}')

X_train dtype: float64


In [60]:
print(X_train.dtype)
print(y_train.dtype)

float64
float64


In [61]:
# Converter X_train e y_train para float32
X_train = np.array(X_train, dtype=np.float32)

Modelagem com LSTM

In [62]:
model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dropout(0.2))
model.add(LSTM(units=50, return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(units=1, activation='sigmoid'))

In [63]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Treinando o modelo
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)

Epoch 1/100
5/5 [==============================] - 1s 68ms/step - loss: 0.6668 - accuracy: 0.6625 - val_loss: 0.6143 - val_accuracy: 0.7000
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6272 - accuracy: 0.6562 - val_loss: 0.5707 - val_accuracy: 0.7000
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6081 - accuracy: 0.6562 - val_loss: 0.5477 - val_accuracy: 0.7000
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6158 - accuracy: 0.6625 - val_loss: 0.5374 - val_accuracy: 0.8000
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6048 - accuracy: 0.6812 - val_loss: 0.5405 - val_accuracy: 0.8000
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6054 - accuracy: 0.7063 - val_loss: 0.5396 - val_accuracy: 0.8000
Epoch 7/100
5/5 [==============================] - 0s 4ms/step - loss: 0.5957 - accuracy: 0.7063 - val_loss: 0.5253 - val_accuracy: 0.8000
Epoch 8/100
5/5 [=========

In [64]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {accuracy:.2f}')

# Previsões
predictions = model.predict(X_test)

2/2 [==============================] - 0s 2ms/step - loss: 0.0678 - accuracy: 0.9804


Test Accuracy: 0.98
2/2 [==============================] - 0s 2ms/step


In [65]:
predictions = model.predict(X_test)

2/2 [==============================] - 0s 954us/step


In [66]:
X_test

array([[[0.00728775, 0.        , 0.01273439, ..., 0.        ,
         0.        , 0.        ]],

       [[0.00193679, 0.        , 0.02333955, ..., 0.        ,
         0.        , 0.        ]],

       [[0.02441874, 0.        , 0.01454885, ..., 0.        ,
         0.        , 0.        ]],

       ...,

       [[0.01463366, 0.01599971, 0.02823718, ..., 0.        ,
         0.        , 0.        ]],

       [[0.02312479, 0.        , 0.02317201, ..., 0.        ,
         0.        , 0.        ]],

       [[0.01484981, 0.        , 0.01826583, ..., 0.        ,
         0.        , 0.        ]]])

In [70]:
predictions.max()

0.99970216

In [71]:
# Converter as predições para rótulos binários
predictions_binary = (predictions > 0.05).astype(int)

In [72]:
predictions_binary

array([[0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0]])

In [73]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

# Calculando métricas
precision = precision_score(y_test, predictions_binary)
recall = recall_score(y_test, predictions_binary)
f1 = f1_score(y_test, predictions_binary)
conf_matrix = confusion_matrix(y_test, predictions_binary)

# Exibindo as métricas
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')
print(f'F1-Score: {f1:.2f}')
print('Confusion Matrix:')
print(conf_matrix)

Precision: 0.77
Recall: 1.00
F1-Score: 0.87
Confusion Matrix:
[[25  6]
 [ 0 20]]
